In [1]:
import gurobipy as gp
from gurobipy import GRB
import numpy as np
import math

In [2]:
itertn=0
size=3 # standard sudoku is 3 that is (3*3)*(3*3)
n=size*size   # length of sudoku matrix
problem=np.zeros((n,n))
m = gp.Model("sudoku solver")


--------------------------------------------
--------------------------------------------

Academic license - for non-commercial use only - expires 2021-05-21
Using license file C:\Users\Satish\gurobi.lic


In [3]:
 while (m.getAttr('SolCount')!=1) and itertn<100 :
    
    itertn=itertn+1
    [iseed,jseed,valseed]=np.random.randint(1,high=10,size=3)
    #print('iseed= ',iseed)
    #print('jseed= ',jseed)
    #print('valseed= ',valseed)
    ix=math.floor(iseed/3)
    jx=math.floor(jseed/3)
    icheckn=(problem[iseed-1,:]==valseed).sum()
    jcheckn=(problem[:,jseed-1]==valseed).sum()
    ijcheckn=(problem[(3*ix):((3*(ix+1))-1),(3*jx):((3*(jx+1))-1)]==valseed).sum()
    if (icheckn==0) and (jcheckn==0) and (ijcheckn==0):  
        problem[iseed-1][jseed-1]=valseed
        #print(problem)
        
        m = gp.Model("sudoku solver")

        # problem is the variable with the problem to be solved. add it as it is in each row with blanks as zero
        m.Params.PoolSearchMode=1
        m.Params.PoolSolutions=2
        sudoku=m.addVars(n,n,n,vtype='b')  
        #The variable is a binary that is, is a number k (0 to 8)(add 1 to visualise) is present in location i,j of sudoku


        for i in range(n):
            for j in range(n):
                for k in range(n):
                    if problem[i][j]==k+1:
                        m.addConstr(sudoku[i,j,k]==1)
        # putting constraints that if a number is given in a problem statement then set the binary value
        # in sudoku variable as one defined above. 

        m.addConstrs(gp.quicksum(sudoku[i,j,k] for k in range(n)) == 1 for i in range(n) for j in range(n))

        # these constraints ensure that only one value (k=0 to 8) == 1 as only one number 
        # occupies the cell i,j of the sudoku solution

        m.addConstrs(gp.quicksum(sudoku[i,j,k] for i in range(n)) == 1 for j in range(n) for k in range(n))

        # constraint that if I add all rows then the k number should be present in j columns
        # or each number should appear in the column atleast once.
        m.addConstrs(gp.quicksum(sudoku[i,j,k] for j in range(n)) == 1 for i in range(n) for k in range(n))

        # constraint that if I add all columns then the k number should be present in i rows
        # or each number should appear in the row atleast once.

        m.addConstrs(gp.quicksum(sudoku[i,j,k] for i in range(a*size,(a+1)*size) for j in range(b*size,(b+1)*size)) == 1 for k in range(n) for a in range(size) for b in range(size) )

        # constraint that if I add all cells in the small square of 3*3 then the k number should be present.
        # or each number should appear in the small square atleast once.

        m.setObjective(0, GRB.MAXIMIZE) # no objective function needed as the constraints are to be followed only to get a solution

        m.ModelSense=GRB.MAXIMIZE                    #set optimization to maximize
        m.update()
        m.optimize()

        if m.getAttr('SolCount')==0:
            problem[iseed-1][jseed-1]=0
        

    


Changed value of parameter PoolSearchMode to 1
   Prev: 0  Min: 0  Max: 2  Default: 0
Changed value of parameter PoolSolutions to 2
   Prev: 10  Min: 1  Max: 2000000000  Default: 10
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 325 rows, 729 columns and 2917 nonzeros
Model fingerprint: 0x13a3bf5c
Variable types: 0 continuous, 729 integer (729 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 5 rows and 29 columns
Presolve time: 0.01s
Presolved: 320 rows, 700 columns, 2800 nonzeros
Variable types: 0 continuous, 700 integer (700 binary)
Found heuristic solution: objective -0.0000000

Explored 0 nodes (0 simplex iterations) in 0.03 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: -0 -0 
No other solutions better than -0

Optim

Changed value of parameter PoolSolutions to 2
   Prev: 10  Min: 1  Max: 2000000000  Default: 10
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 331 rows, 729 columns and 2923 nonzeros
Model fingerprint: 0x52f1b37f
Variable types: 0 continuous, 729 integer (729 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 36 rows and 183 columns
Presolve time: 0.01s
Presolved: 295 rows, 546 columns, 2181 nonzeros
Variable types: 0 continuous, 546 integer (546 binary)
Found heuristic solution: objective -0.0000000

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: -0 -0 
No other solutions better than -0

Optimal solution found (tolerance 1.00e-04)
Best objective -0.000000000000e+00, best boun

Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 79 rows and 320 columns
Presolve time: 0.00s
Presolved: 258 rows, 409 columns, 1629 nonzeros
Variable types: 0 continuous, 409 integer (409 binary)
Found heuristic solution: objective -0.0000000

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: -0 -0 
No other solutions better than -0

Optimal solution found (tolerance 1.00e-04)
Best objective -0.000000000000e+00, best bound -0.000000000000e+00, gap 0.0000%
Changed value of parameter PoolSearchMode to 1
   Prev: 0  Min: 0  Max: 2  Default: 0
Changed value of parameter PoolSolutions to 2
   Prev: 10  Min: 1  Max: 2000000000  Default: 10
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 338 


Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: -0 -0 
No other solutions better than -0

Optimal solution found (tolerance 1.00e-04)
Best objective -0.000000000000e+00, best bound -0.000000000000e+00, gap 0.0000%
Changed value of parameter PoolSearchMode to 1
   Prev: 0  Min: 0  Max: 2  Default: 0
Changed value of parameter PoolSolutions to 2
   Prev: 10  Min: 1  Max: 2000000000  Default: 10
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 344 rows, 729 columns and 2936 nonzeros
Model fingerprint: 0x9a07fd01
Variable types: 0 continuous, 729 integer (729 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 123 rows and 461 columns
Presolve time: 0.00s

Explored 0 nodes (0 simplex

Best objective -0.000000000000e+00, best bound -0.000000000000e+00, gap 0.0000%
Changed value of parameter PoolSearchMode to 1
   Prev: 0  Min: 0  Max: 2  Default: 0
Changed value of parameter PoolSolutions to 2
   Prev: 10  Min: 1  Max: 2000000000  Default: 10
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 346 rows, 729 columns and 2938 nonzeros
Model fingerprint: 0x47d159ef
Variable types: 0 continuous, 729 integer (729 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 267 rows and 638 columns
Presolve time: 0.00s
Presolved: 79 rows, 91 columns, 339 nonzeros
Variable types: 0 continuous, 91 integer (91 binary)
Found heuristic solution: objective -0.0000000

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 8 (of 8 available 

In [4]:
solution=np.zeros((n,n))

for i in range(n):
    for j in range(n):
        for k in range(n):
            if sudoku[i,j,k].x>0.5:
                solution[i,j]=k+1


    # checking the solution and getting the values in the matrix. 

print(solution)

print(problem)

print(m.getAttr('SolCount'))

[[6. 5. 9. 4. 7. 1. 3. 2. 8.]
 [4. 7. 3. 8. 2. 9. 6. 5. 1.]
 [1. 2. 8. 3. 6. 5. 7. 9. 4.]
 [9. 8. 6. 2. 5. 4. 1. 7. 3.]
 [2. 1. 4. 9. 3. 7. 8. 6. 5.]
 [7. 3. 5. 6. 1. 8. 9. 4. 2.]
 [5. 6. 1. 7. 4. 3. 2. 8. 9.]
 [3. 9. 7. 5. 8. 2. 4. 1. 6.]
 [8. 4. 2. 1. 9. 6. 5. 3. 7.]]
[[6. 0. 9. 0. 0. 0. 0. 0. 0.]
 [4. 7. 0. 8. 2. 0. 0. 5. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [0. 8. 0. 0. 0. 0. 0. 7. 0.]
 [2. 1. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 9. 4. 2.]
 [0. 6. 1. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 0. 7.]]
1


In [5]:
problem

array([[6., 0., 9., 0., 0., 0., 0., 0., 0.],
       [4., 7., 0., 8., 2., 0., 0., 5., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [0., 8., 0., 0., 0., 0., 0., 7., 0.],
       [2., 1., 0., 0., 3., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 9., 4., 2.],
       [0., 6., 1., 0., 4., 0., 0., 0., 0.],
       [0., 0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 5., 0., 7.]])

In [6]:
solution

array([[6., 5., 9., 4., 7., 1., 3., 2., 8.],
       [4., 7., 3., 8., 2., 9., 6., 5., 1.],
       [1., 2., 8., 3., 6., 5., 7., 9., 4.],
       [9., 8., 6., 2., 5., 4., 1., 7., 3.],
       [2., 1., 4., 9., 3., 7., 8., 6., 5.],
       [7., 3., 5., 6., 1., 8., 9., 4., 2.],
       [5., 6., 1., 7., 4., 3., 2., 8., 9.],
       [3., 9., 7., 5., 8., 2., 4., 1., 6.],
       [8., 4., 2., 1., 9., 6., 5., 3., 7.]])

In [7]:
for i in range(1):
    [iseed,jseed,valseed]=np.random.randint(1,high=9,size=3)
    
    
    
    problem[iseed-1][jseed-1]=valseed

print(problem)

[[6. 0. 9. 0. 0. 0. 0. 0. 0.]
 [4. 7. 0. 8. 2. 0. 0. 5. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [0. 8. 0. 0. 0. 0. 0. 7. 0.]
 [2. 1. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 9. 4. 2.]
 [0. 6. 1. 5. 4. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 0. 7.]]


In [8]:
icheck=np.zeros((9,))
for i in range(9):
    icheck[i]=(problem[i,:]==valseed).sum()

jcheck=np.zeros((9,))
for j in range(9):
    jcheck[j]=(problem[:,j]==valseed).sum()

    
ijcheck=np.zeros(9,)
for i in range(3):
    for j in range(3):
        ijcheck[i+(3*j)]=(problem[(3*i):(3*(i+1)),(3*j):(3*(j+1))]==valseed).sum()


In [9]:
icheck

array([0., 1., 0., 0., 0., 0., 1., 1., 1.])

In [10]:
jcheck

array([0., 0., 0., 2., 0., 0., 1., 1., 0.])

In [11]:
valseed

5

In [12]:
ijcheck

array([0., 0., 0., 0., 0., 2., 1., 0., 1.])

In [13]:
ix=math.floor(iseed/3)
jx=math.floor(jseed/3)


icheckn=(problem[iseed,:]==valseed).sum()
jcheckn=(problem[:,jseed]==valseed).sum()
ijcheckn=(problem[(3*ix):(3*(ix+1)),(3*jx):(3*(jx+1))]==valseed).sum()


In [14]:
icheckn

1

In [15]:
jcheckn

0

In [16]:
ijcheckn

2

In [17]:
iseed

7

In [18]:
jseed

4

In [19]:
valseed

5

In [20]:
problem

array([[6., 0., 9., 0., 0., 0., 0., 0., 0.],
       [4., 7., 0., 8., 2., 0., 0., 5., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [0., 8., 0., 0., 0., 0., 0., 7., 0.],
       [2., 1., 0., 0., 3., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 9., 4., 2.],
       [0., 6., 1., 5., 4., 0., 0., 0., 0.],
       [0., 0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 5., 0., 7.]])

In [21]:
m.getAttr('SolCount')

1

In [22]:
m.getAttr('SolCount')!=1

False